set_property PACKAGE_PIN Y18 [get_ports sys_clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk_i]
set_property PACKAGE_PIN M15 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property PACKAGE_PIN F15 [get_ports btn_reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports btn_reset_n]

set_property PACKAGE_PIN M22 [get_ports {leds[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property PACKAGE_PIN N22 [get_ports {leds[1]}]
set_property PACKAGE_PIN L21 [get_ports {leds[2]}]
set_property PACKAGE_PIN K21 [get_ports {leds[3]}]
set_property PACKAGE_PIN K22 [get_ports {leds[4]}]
set_property PACKAGE_PIN J22 [get_ports {leds[5]}]
set_property PACKAGE_PIN H22 [get_ports {leds[6]}]
set_property PACKAGE_PIN M21 [get_ports {leds[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[7]}]

create_clock -period 20.000 -name sys_clk_i -waveform {0.000 10.000} [get_ports sys_clk_i]
