set_property SRC_FILE_INFO {cfile:/pro/fpga/risc-v/risc-v.srcs/constrs_1/new/ACX720-V3.xdc rfile:../../../risc-v.srcs/constrs_1/new/ACX720-V3.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y18 [get_ports sys_clk]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports uart_tx]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15 [get_ports btn_reset_n]
